version: '3.8'

services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual.
    build:
      context: .
      # Especifica o nome do arquivo, já que não é o padrão "Dockerfile".
      dockerfile: dockerfile
    
    # Nomeia o contêiner para fácil referência.
    container_name: api

    # Mapeia a porta 8000 do host para a porta 8000 do contêiner.
    ports:
      - "8001:8000"

    # Monta um volume nomeado para persistir o banco de dados SQLite.
    volumes:
      - escola-db-data:/app

volumes:
  # Define o volume que será gerenciado pelo Docker.
  escola-db-data: